### ISSUE TITLE
Error in TypeScript compilation: Cannot find name 'StdioOverrideFunction'

### ISSUE THREAD

**Issue by bvobart** [moshen/wasmagic#40]
Hi, I'm trying to use your library in a project for work, but running `npm run build` in our project fails due to the following error:

```
node_modules/wasmagic/dist/index.d.ts:63:13 - error TS2304: Cannot find name 'StdioOverrideFunction'.

63     stdio?: StdioOverrideFunction;
               ~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/wasmagic/dist/index.d.ts:63
```

I see that the mentioned `StdioOverrideFunction` is defined in the `types` folder in this repo, but not in `src/index.ts` and it's apparent that the TypeScript compiler isn't including that type into the final `dist/index.d.ts`.

Can you fix this? It's breaking TypeScript builds at the moment.

**Comment by bvobart** [comment]
Note: I created a patch file with `patch-package` to work around the issue for now. Here's the patch file:

```patch
diff --git a/node_modules/wasmagic/dist/index.d.ts b/node_modules/wasmagic/dist/index.d.ts
index a4bc2f5..c59e913 100644
--- a/node_modules/wasmagic/dist/index.d.ts
+++ b/node_modules/wasmagic/dist/index.d.ts
@@ -56,6 +56,10 @@ export declare enum WASMagicFlags {
     /** Don't check for SIMH tape files */
     NO_CHECK_SIMH = 8388608
 }
+export type StdioOverrideFunction = (
+    stdioName: "stdout" | "stderr",
+    text: string,
+) => void;
 export type WASMagicOptions = {
     flags?: WASMagicFlags;
     loadDefaultMagicfile?: boolean;
```

**Comment by moshen** [comment]
Thanks! Sorry about that. I'll get this integrated. I haven't run into this when testing myself

**Comment by moshen** [comment]
A little bit of fighting with the Typescript type system for the type to not only be exposed in the library, but to work in-editor for library maintenance. My original solution, and your patch @bvobart were flawed, in that local development of the library with type checking was broken.

As the `StdioOverrideFunction` hook is injected when the C wrapper is built with Emscripten, I had to move the type definition into it's own file and re-export it to use ergonomically in the library.

Thank you for the bug report

**Comment by bvobart** [comment]
Thanks for your efforts!! Yeah, my patch was aimed at the final compiled & published artifacts, I don't know exactly how that relates back to your source code.

However, the issue is not yet fixed. It seems that your fix now doubly includes the `StdioOverrideFunction`: there's both an `import StdioOverrideFunction from ..; export { default as StdioOverrideFunction } from ..` as well as another declaration `export type StdioOverrideFunction`, causing the following errors when I try to compile my project with the latest version of wasmagic:

```
node_modules/wasmagic/dist/index.d.ts:1:8 - error TS2395: Individual declarations in merged declaration 'StdioOverrideFunction' must be all exported or all local.

1 import StdioOverrideFunction from "./StdioOverrideFunction";
         ~~~~~~~~~~~~~~~~~~~~~

node_modules/wasmagic/dist/index.d.ts:1:8 - error TS2440: Import declaration conflicts with local declaration of 'StdioOverrideFunction'.

1 import StdioOverrideFunction from "./StdioOverrideFunction";
         ~~~~~~~~~~~~~~~~~~~~~

node_modules/wasmagic/dist/index.d.ts:2:10 - error TS2484: Export declaration conflicts with exported declaration of 'StdioOverrideFunction'.

2 export { default as StdioOverrideFunction } from "./StdioOverrideFunction";
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/wasmagic/dist/index.d.ts:61:13 - error TS2395: Individual declarations in merged declaration 'StdioOverrideFunction' must be all exported or all local.

61 export type StdioOverrideFunction = (
               ~~~~~~~~~~~~~~~~~~~~~


Found 4 errors in the same file, starting at: node_modules/wasmagic/dist/index.d.ts:1
```

I'll fork and play around to see if I can fix it in your source code / build process. I'll report back when I have a PR, but of course feel free to fix it yourself in the mean time too :)

**Comment by moshen** [comment]
Do you have an example of usage / Typescript settings? I'm probably missing something here. When I import into another typescript project it compiles without any complaints. [The other solution I arrived at was aliasing the type and re-exporting it.](https://github.com/moshen/wasmagic/commit/84188c997405a0000bc016076d8aea6b75c5ab4f#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80)

The only issue with that was more the editor didn't expose the underlying type, but that's not a big deal. Can revert to that if it works.

**Comment by moshen** [comment]
I made this working Typescript example: https://gist.github.com/moshen/a73cd974547363fc37e26874c925f6ae

**Comment by bvobart** [comment]
Hmmmmm, this is strange. I tried out your working example and it worked just fine. I was trying to compare between my work project and your example, also to make a MWE showing the bug, but now somehow the issue is fixed. Perhaps there was still an old version around on my system somehow, I don't know.

Anyways, it magically started working and my CI is happy too.

Thanks a lot for your help and your quick replies! 😊
